image: docker:latest
stages:
  - build

before_script:
  - docker info
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

build_container:
  only:
    - branches@liquid/stats
  stage: build
  script:
    - docker pull blockstream/liquid-stats:latest || true
    - docker build
        --cache-from blockstream/liquid-stats:latest
        -f Dockerfile
        -t blockstream/liquid-stats:latest .
    - docker push blockstream/liquid-stats:latest
    - docker rmi blockstream/liquid-stats:latest
